module.exports = [
  'swingers club',
  'swinging club',
  'lifestyle club',
  'adult lifestyle club',
  'private members club',
  'couples club',
  'adult social club',
  'fetish club',
  'kink club',
  'bdsm club',
  'play party',
  'gay sauna',
  'adult spa',
  'swingers venue',
  'lifestyle venue',
  'fetish events',
  'kink events',
  'social events couples',
]